server:
  port: 8080

spring:
  application:
    name: chatapp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

openrouter:
  api-url: "https://openrouter.ai/api/v1/chat/completions"
  api-key: "123"  # Placeholder for your individual API key
  model: "openai/gpt-oss-20b:free"  # OpenRouter GPT OSS 20B free model

logging:
  level:
    com.example.chatapp: DEBUG
    org.springframework.web: DEBUG
